development:
  adapter: mysql2
  encoding: utf8
  database: demo6_development
  host: localhost
  username: root
  password:

test:
  adapter: mysql2
  encoding: utf8
  database: demo6_test
  host: localhost
  username: root
  password:

production:
  adapter: mysql2
  encoding: utf8
  database: demo6_production
  host: localhost
  username: root
  password:
